# Copyright 2014-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
#	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

FROM golang:1.4
MAINTAINER Amazon Web Services, Inc.

RUN mkdir /out
VOLUME ['/out']

RUN mkdir -p /go/src/github.com/aws/
RUN go get github.com/tools/godep

# For gomock
RUN go get code.google.com/p/gomock/gomock
#RUN go install code.google.com/p/gomock/gomock

RUN go get code.google.com/p/gomock/mockgen
#RUN go install code.google.com/p/gomock/mockgen

RUN go get golang.org/x/tools/cmd/goimports

COPY scripts/build /scripts/build
# For gomock
COPY /scripts/mockgen.sh /scripts/mockgen.sh
WORKDIR /go/src/github.com/aws/amazon-ecs-agent

ENTRYPOINT /scripts/build
